name: 'Pull Request Action 🚀'

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/github-script@0.3.0
         if: github.event_name == 'pull_request'
         with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
           const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
           github.issues.createComment({ issue_number, owner, repo, body: `{author}` + `thanks for submitting a pull request! We will try to review it as soon as we can :)` });
